name: rmac-build-cosmo
on:
  workflow_dispatch:
  push:
  
jobs:
  build_cosmo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - run: |
            mkdir -p cosmocc
            cd cosmocc
            wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
            unzip cosmocc.zip
            cd ..
            export PATH=$PATH:$PWD/cosmocc/bin
            git clone http://tiddly.mooo.com:5000/rmac/rmac.git
            git clone http://tiddly.mooo.com:5000/rln/rln.git
            mkdir output
            cd rmac
            sed -i -e "s/(CROSS)gcc/(CROSS)cosmocc/gI" makefile
            make -j2
            strip rmac
            mv rmac ../output
            cd ../rln
            sed -i -e "s/(CROSS)gcc/(CROSS)cosmocc/gI" makefile
            make -j2
            strip rln
            mv rln ../output

      - name: "Upload rmac"
        uses: actions/upload-artifact@v4
        with:
          name: rmac_cosmo-x64-${{ github.sha }}
          path: output/rmac

      - name: "Upload rln"
        uses: actions/upload-artifact@v4
        with:
          name: rln_cosmo-x64-${{ github.sha }}
          path: output/rln

