name: rmac-build-alpine
on:
  workflow_dispatch:
  push:
  
jobs:
  build_leenueks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            gcc
            binutils
            make
            musl-dev
            git
            zip

      - shell: alpine.sh --root {0}
        run: |
            git clone http://shamusworld.gotdns.org/git/rmac
            git clone http://shamusworld.gotdns.org/git/rln
            mkdir output
            cd rmac
            sed -i -e "s/CFLAGS = /CFLAGS = -static /gI" makefile
            make -j8
            strip rmac
            mv rmac ../output
            cd ../rln
            sed -i -e "s/CFLAGS = /CFLAGS = -static /gI" makefile
            make -j8
            strip rln
            mv rln ../output

            #      - name: zip outputs
            #        shell: alpine.sh --root {0}
            #        run: |
            #          cd output
            #          zip -r rmac-rln-linux.zip rmac rln

      - name: "Upload rmac"
        uses: actions/upload-artifact@v4
        with:
          name: rmac_linux-x64-${{ github.sha }}
          path: output/rmac

      - name: "Upload rln"
        uses: actions/upload-artifact@v4
        with:
          name: rln-linux-x64-${{ github.sha }}
          path: output/rln

  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          #githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            apt-get update -q -y
            apt-get install -q -y git gcc make zip
            git clone http://shamusworld.gotdns.org/git/rmac
            git clone http://shamusworld.gotdns.org/git/rln
            mkdir output
            cd rmac
            sed -i -e "s/CFLAGS = /CFLAGS = -static /gI" makefile
            make -j8
            strip rmac
            mv rmac ../output
            cd ../rln
            sed -i -e "s/CFLAGS = /CFLAGS = -static /gI" makefile
            make -j8
            strip rln
            mv rln ../output
            #cd ../output
            #zip -r rmac-rln-linux.zip rmac rln

      - name: "Upload rmac"
        uses: actions/upload-artifact@v4
        with:
          name: rmac_linux-aarch64-${{ github.sha }}
          path: output/rmac

      - name: "Upload rln"
        uses: actions/upload-artifact@v4
        with:
          name: rln-linux-aarch64-${{ github.sha }}
          path: output/rln

          
