name: rmac-build-mingw
on:
  workflow_dispatch:
  push:

jobs:
  build_mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, toolchain: mingw-w64-x86_64-toolchain, gcc_package_name: mingw-w64-x86_64-gcc, gcc_name: x86_64-w64-mingw32-gcc },
          { msystem: MINGW32, toolchain: mingw-w64-i686-toolchain, gcc_package_name: mingw-w64-i686-gcc, gcc_name: i686-w64-mingw32-gcc  },
        ]
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: zip VCS binutils pactoys-git ${{ matrix.gcc_package_name }} make
          #${{ matrix.toolchain }} base-devel 

      - name: "Build all the things"
        shell: msys2 {0}
        run: |
          git clone http://shamusworld.gotdns.org/git/rmac
          git clone http://shamusworld.gotdns.org/git/rln
          mkdir output
          cd rmac
          sed -i "s/gcc$/${{ matrix.gcc_name }}/g" makefile
          make -j2
          strip rmac.exe
          mv rmac.exe ../output
          cd ../rln
          sed -i "s/gcc$/${{ matrix.gcc_name }}/g" makefile
          make -j2
          strip rln.exe
          mv rln.exe ../output

      - name: zip outputs
        shell: msys2 {0}
        run: |
          cd output
          zip -r rmac-rln-${{ matrix.msystem }}.zip rmac.exe rln.exe

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: rmac_rln-mingw-${{ github.sha }}
          path: output/*.zip

