# Macos Build

name: rmac-build-osx12

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_osx_12:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Do the work
        run: |
          git clone http://tiddly.mooo.com:5000/rmac/rmac.git
          cd rmac
          mkdir output
          # Apply the secret sauce
          sed -i -e "s/CFLAGS = /CFLAGS = -target arm64-apple-macos11/g" makefile
          sed -i -e "s/\$(HOSTCC) \$(CFLAGS)/\$(HOSTCC)/g" makefile
          make -j 3
          file rmac
          strip rmac
          mv rmac output
          cd ..
          git clone http://tiddly.mooo.com:5000/rln/rln.git
          cd rln
          sed -i -e "s/CFLAGS = /CFLAGS = -target arm64-apple-macos11/g" makefile
          make -j 3
          file rln
          strip rln
          mv rln ../rmac/output

      - name: "Upload rmac"
        uses: actions/upload-artifact@v4
        with:
          name: rmac_osx-12-${{ github.sha }}
          path: rmac/output/rmac

      - name: "Upload rln"
        uses: actions/upload-artifact@v4
        with:
          name: rln-osx-12-${{ github.sha }}
          path: rmac/output/rln
