name: rmac-build-vs
on:
  workflow_dispatch:
  push:

jobs:
  build_vs:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Download and install Windows SDK
        run: |
          import subprocess
          import urllib.request
          urllib.request.urlretrieve("https://go.microsoft.com/fwlink/p/?LinkId=323507", "sdksetup.exe")
          subprocess.run(["sdksetup.exe", "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"], check=True, capture_output=True)
        shell: python

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: "Clone and build all the things"
        shell: cmd
        run: |
          git clone http://tiddly.mooo.com:5000/rmac/rmac.git
          git clone http://tiddly.mooo.com:5000/rln/rln.git
          echo ------------------------------------------------------x86 rmac
          msbuild "rmac\Vs2015\VS2015.sln" /p:configuration=Release /p:platform=x86 /p:PlatformToolset=v142
          cd rmac
          7z a ..\rmac_x86.zip rmac.exe
          cd ..
          echo ------------------------------------------------------x64 rmac
          del rmac.exe
          msbuild "rmac\Vs2015\VS2015.sln" /p:configuration=Release /p:platform=x64 /p:PlatformToolset=v142
          cd rmac
          7z a ..\rmac_x64.zip rmac.exe
          cd ..
          echo ------------------------------------------------------x86 rln
          rem curl https://github.com/tronkko/dirent/blob/master/include/dirent.h --output rln\dirent.h
          msbuild "rln\VS2015\VS2015.sln" /p:configuration=Release /p:platform=x86 /p:PlatformToolset=v142
          cd rln
          7z a ..\rln_x86.zip rln.exe
          cd ..
          echo ------------------------------------------------------x64 rln
          del rmac.exe
          msbuild "rln\VS2015\VS2015.sln" /p:configuration=Release /p:platform=x64 /p:PlatformToolset=v142
          cd rmac
          7z a ..\rmac_x64.zip rln.exe
          cd ..

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: rmac_rln-vs-${{ github.sha }}
          path: .

